### ISSUE TITLE
Error 'hash'

### ISSUE THREAD

**Issue by tomillo** [davidmckenzie/telebagger#1]
Hi! I'm trying to get it work, but console says:

```
Traceback (most recent call last):
  File "telebagger.py", line 96, in <module>
    min_id=0
TypeError: __init__() missing 1 required positional argument: 'hash'
```

Can you help me?

**Comment by davidmckenzie** [comment]
Ah, I fixed that in telelooper.py but not telebagger.py. The telelooper.py version is better to use in most cases though as it doesn't miss messages in supergroups. Will update readme :)

**Comment by tomillo** [comment]
Good job!

**Comment by tomillo** [comment]
One more question.. how to remove @everyone for messages?

**Comment by davidmckenzie** [comment]
In the config:
```
        "everyone":true,
```
Just change that to false and should be sweet

**Comment by tomillo** [comment]
Thanks man. Supports multi-channel relays?

**Comment by davidmckenzie** [comment]
Nope but you can run multiple instances fine - you'd just clone the directory and have different channel IDs in each.

**Comment by tomillo** [comment]
> Nope but you can run multiple instances fine - you'd just clone the directory and have different channel IDs in each.

@davidmckenzie can't use more than three instances.
