### ISSUE TITLE
Relay images

### ISSUE THREAD

**Issue by tomillo** [davidmckenzie/telebagger#2]
There's a way to relays images too, or maybe copying the url?

**Comment by davidmckenzie** [comment]
Yeah that's something I'm planning on looking at in the future, but not on the priority list at the moment :)

If you wanted to have a crack at it, telethon has a download_media function that can be called when processing the message.

**Comment by tomillo** [comment]
Thanks @davidmckenzie, i'm going to find download_media function.

Is it possible to relay messages with reply/quote too?
