### ISSUE TITLE
unexpected keyword argument 'update_workers'

### ISSUE THREAD

**Issue by hubavka** [davidmckenzie/telebagger#6]
File "telelooper.py", line 42, in <module>
    tclient = TelegramClient('session_name', api_id, api_hash, update_workers=4, spawn_read_thread=False)
TypeError: __init__() got an unexpected keyword argument 'update_workers'

**Comment by arjunnai** [comment]
update_workers and spawn_read_thread are deprecated.
You can remove them from the function and it'll run without errors
